# Generated by Django 4.1.7 on 2023-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HospitalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("country", models.CharField(max_length=200, null=True)),
                ("region", models.CharField(max_length=200, null=True)),
                ("address", models.TextField(null=True)),
                ("website_url", models.URLField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("hotline", models.CharField(max_length=15, null=True)),
                ("operating_hours", models.CharField(max_length=50, null=True)),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Private", "Private"),
                            ("Public", "Public"),
                            ("Non-Profit", "Non Profit"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
                (
                    "facility_level",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Primary", "Primary"),
                            ("Secondary", "Secondary"),
                            ("Tetiary", "Tetiary"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("General", "General"),
                            ("Specialist", "Specialist"),
                            ("Teaching", "Teaching"),
                        ],
                        default="None",
                        max_length=15,
                    ),
                ),
                (
                    "services_offered",
                    models.CharField(blank=True, max_length=30000, null=True),
                ),
                ("bed_spaces", models.IntegerField(default=0)),
                (
                    "other_facilities",
                    models.CharField(blank=True, max_length=30000, null=True),
                ),
            ],
        ),
    ]
