# Generated by Django 4.1.7 on 2023-03-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HospitalDetails",
            new_name="HospitalDetail",
        ),
    ]
