# Generated by Django 4.1.7 on 2023-03-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_hospitaldetail_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitaldetail",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
