# Generated by Django 4.1.7 on 2023-03-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_hospitaldetail_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitaldetail",
            old_name="name",
            new_name="hospital_name",
        ),
    ]
