# Generated by Django 4.1.7 on 2023-03-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_rename_name_hospitaldetail_hospital_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitaldetail",
            name="city",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
